use onsoon;
-- delete from vne_response_payment;
delete from onsoon.b_foods;
delete from onsoon.b_foods_category;
delete from onsoon.b_foods_category_sub;
delete from onsoon.b_foods_material;
delete from onsoon.b_foods_recommend;
delete from onsoon.b_foods_special;
delete from onsoon.b_foods_topping;
delete from onsoon.b_foods_type;
delete from onsoon.b_material;
delete from onsoon.b_material_type;
delete from onsoon.b_noodle_make;
delete from onsoon.t_bill;
delete from onsoon.t_bill_detail;
delete from onsoon.t_closeday;
delete from onsoon.t_material_draw;
delete from onsoon.t_material_draw_detail;
delete from onsoon.t_material_rec;
delete from onsoon.t_material_rec_detail;
delete from onsoon.t_order;
delete from onsoon.t_order_material;
delete from onsoon.t_order_special;
delete from onsoon.t_order_topping;
delete from onsoon.t_stock;
delete from onsoon.t_stock_endyear;
delete from onsoon.vne_close_day;
delete from onsoon.vne_request_payment;
delete from onsoon.vne_response_payment;

UPDATE onsoon.sequence SET lotid=0;
ALTER TABLE onsoon.b_foods AUTO_INCREMENT = 1040000000;
ALTER TABLE onsoon.b_foods_category AUTO_INCREMENT = 1030000000;
ALTER TABLE onsoon.b_foods_category_sub AUTO_INCREMENT = 1050000000;
ALTER TABLE onsoon.b_foods_material AUTO_INCREMENT = 1410000000;
ALTER TABLE onsoon.b_foods_recommend AUTO_INCREMENT = 1060000000;
ALTER TABLE onsoon.b_foods_special AUTO_INCREMENT = 1280000000;
ALTER TABLE onsoon.b_foods_topping AUTO_INCREMENT = 1290000000;
ALTER TABLE onsoon.b_foods_type AUTO_INCREMENT = 1020000000;
ALTER TABLE onsoon.b_material AUTO_INCREMENT = 1400000000;
ALTER TABLE onsoon.b_material_type AUTO_INCREMENT = 1420000000;
ALTER TABLE onsoon.b_noodle_make AUTO_INCREMENT = 1130000000;
ALTER TABLE onsoon.t_bill AUTO_INCREMENT = 1070000000;
ALTER TABLE onsoon.t_bill_detail AUTO_INCREMENT = 1080000000;
ALTER TABLE onsoon.t_closeday AUTO_INCREMENT = 1090000000;
ALTER TABLE onsoon.t_material_draw AUTO_INCREMENT = 1470000000;
ALTER TABLE onsoon.t_material_draw_detail AUTO_INCREMENT = 1480000000;
ALTER TABLE onsoon.t_material_rec AUTO_INCREMENT = 1450000000;
ALTER TABLE onsoon.t_material_rec_detail AUTO_INCREMENT = 1460000000;
ALTER TABLE onsoon.t_order AUTO_INCREMENT = 1100000000;
ALTER TABLE onsoon.t_order_material AUTO_INCREMENT = 1430000000;
ALTER TABLE onsoon.t_order_special AUTO_INCREMENT = 1320000000;
ALTER TABLE onsoon.t_order_topping AUTO_INCREMENT = 1310000000;
ALTER TABLE onsoon.t_stock AUTO_INCREMENT = 1490000000;
ALTER TABLE onsoon.t_stock_endyear AUTO_INCREMENT = 1500000000;
ALTER TABLE onsoon.vne_close_day AUTO_INCREMENT = 151000000;
ALTER TABLE onsoon.vne_request_payment AUTO_INCREMENT = 152000000;
ALTER TABLE onsoon.vne_response_payment AUTO_INCREMENT = 1530000000;

